### ISSUE TITLE
the code is not working and returns 3 errors 

### ISSUE THREAD

**Issue by abdelrahmanelmarakby** [eslam-mahmoud/GolangForBeginners.com#1]
```
for i := 0; i < 3; i++ {
			// check rows || columns
			if (xoBoard[i][0] == xoBoard[i][1] && xoBoard[i][1] == xoBoard[i][2] && xoBoard[i][2] == player || (xoBoard[0][i] == xoBoard[1][i] && xoBoard[1][i] == xoBoard[2][i] && xoBoard[2][i] == player){
				fmt.Println("Game ended, winner is player:", player)
				// we use return to exit both for loops and the app
				return
			}
		}
		if (xoBoard[0][0] == xoBoard[1][1] && xoBoard[1][1] == xoBoard[2][2] && xoBoard[2][2] == player) || (xoBoard[0][2] == xoBoard[1][1] && xoBoard[1][1] == xoBoard[2][0] && xoBoard[2][0] == player) {
			fmt.Println("Game ended, winner is player:", player)
			// end the game and exit the app
			// we can use "break" or "return"
			return
		}`
```
the errors are 
1-{
	"resource": "/c:/Users/aa/Desktop/golang/XOgame.go",
	"owner": "go",
	"severity": 8,
	**"message": "syntax error: unexpected {, expecting )",**
	"source": "go",
	"startLineNumber": 49,
	"startColumn": 196,
	"endLineNumber": 49,
	"endColumn": 197
}
2-{
	"resource": "/c:/Users/aa/Desktop/golang/XOgame.go",
	"owner": "go",
	"severity": 8,
	**"message": "syntax error: unexpected fmt, expecting {",**
	"source": "go",
	"startLineNumber": 50,
	"startColumn": 5,
	"endLineNumber": 50,
	"endColumn": 57
}
3-{
	"resource": "/c:/Users/aa/Desktop/golang/XOgame.go",
	"owner": "go",
	"severity": 8,
	**"message": "syntax error: unexpected return, expecting expression",**
	"source": "go",
	"startLineNumber": 52,
	"startColumn": 5,
	"endLineNumber": 52,
	"endColumn": 11
}

**Comment by eslam-mahmoud** [comment]
Thanks for pointing this out
fixed in this commit https://github.com/eslam-mahmoud/GolangForBeginners.com/commit/daa02851b236d1b3c0bb385bfa0a78a7e108f6d2
there was a syntax error missing `)`
